import { Word } from '../wordstruct/word';

export const CityPlacesRu: Word[] = [
    new Word(-100, '', '', ['', '', '', '', '', '', '', '', '', '']),
    new Word(111, 'город', '', ['city', 'town', '', '', '', '', '', '', '', '']),
    new Word(112, 'здание', '', ['house', 'building', '', '', '', '', '', '', '', '']),
    new Word(113, 'дом', '', ['home', 'house', '', '', '', '', '', '', '', '']),
    new Word(114, 'строительство', '', ['building', '', '', '', '', '', '', '', '', '']),
    new Word(115, 'место', '', ['place', '', '', '', '', '', '', '', '', '']),
    new Word(116, 'вход', '', ['entrance', '', '', '', '', '', '', '', '', '']),
    new Word(117, 'выход', '', ['', 'exit', '', '', '', '', '', '', '', '']),
    new Word(118, 'центр', '', ['center', '', '', '', '', '', '', '', '', '']),
    new Word(119, 'двор', '', ['court', 'yard', 'garth', '', '', '', '', '', '', '']),

    new Word(120, 'крыша', '', ['roof', 'housetop', '', '', '', '', '', '', '', '']),
    new Word(121, 'забор', '', ['fance', 'fancing', 'palisade', '', '', '', '', '', '', '']),
    new Word(122, 'земля', '', ['earth', 'land', 'ground', 'territory', 'terra', 'sod', '', '', '', '']),
    new Word(123, 'деревня', '', ['village', 'countryside', 'country', 'hamlet', '', '', '', '', '', '']),
    new Word(124, 'школа', '', ['school', 'academy', '', '', '', '', '', '', '', '']),
    new Word(125, 'университет', '', ['college', 'university', 'varsity', 'campus', '', '', '', '', '', '']),
    new Word(126, 'театр', '', ['theater', 'theatre', '', '', '', '', '', '', '', '']),
    new Word(127, 'церковь', '', ['chapel', 'church', 'kirk', '', '', '', '', '', '', '']),
    new Word(128, 'ресторан', '', ['restaurant', '', '', '', '', '', '', '', '', '']),
    new Word(129, 'кафе', '', ['cafe', '', '', '', '', '', '', '', '', '']),

    new Word(130, 'гостиница', '', ['hotel', 'hostel', 'guesthouse', '', '', '', '', '', '', '']),
    new Word(131, 'банк', '', ['bank', '', '', '', '', '', '', '', '', '']),
    new Word(132, 'кинотеатр', '', ['cinema', '', '', '', '', '', '', '', '', '']),
    new Word(133, 'больница', '', ['hospital', '', '', '', '', '', '', '', '', '']),
    new Word(134, 'полиция', '', ['police', '', '', '', '', '', '', '', '', '']),
    new Word(135, 'почта', '', ['post office', 'mail', 'post', '', '', '', '', '', '', '']),
    new Word(136, 'станция', '', ['station', '', '', '', '', '', '', '', '', '']),
    new Word(136, 'вокзал', '', ['railway station', 'depot', 'terminus', 'terminal', '', '', '', '', '', '']),
    new Word(137, 'аэропорт', '', ['airport', '', '', '', '', '', '', '', '', '']),
    new Word(138, 'магазин', '', ['store', 'shop', 'magazine', '', '', '', '', '', '', '']),
    new Word(139, 'аптека', '', ['pharmacy', 'drugstore', '', '', '', '', '', '', '', '']),

    new Word(140, 'рынок', '', ['market', '', '', '', '', '', '', '', '', '']),
    new Word(141, 'офис', '', ['office', '', '', '', '', '', '', '', '', '']),
    new Word(142, 'компания', '', ['company', 'firm', '', '', '', '', '', '', '', '']),
    new Word(143, 'предприятие', '', ['enterprise', 'company', 'concern', '', '', '', '', '', '', '']),
    new Word(143, 'фабрика', '', ['factory', 'manufactory', 'plant', '', '', '', '', '', '', '']),
    new Word(143, 'завод', '', ['factory', 'plant', '', '', '', '', '', '', '', '']),
    new Word(144, 'площадь', '', ['area', 'square', 'place', 'space', '', '', '', '', '', '']),
    new Word(145, 'улица', '', ['street', 'road', 'outdoors', '', '', '', '', '', '', '']),
    new Word(146, 'дорога', '', ['road', 'way', 'driveway', 'route', 'ride', '', '', '', '', '']),
    new Word(147, 'перекресток', '', ['intersection', 'crossroad', 'crossway', '', '', '', '', '', '', '']),
    new Word(148, 'остановка', '', ['stop', 'halt', 'stay', 'pause', '', '', '', '', '', '']),
    new Word(149, 'тротуар', '', ['sidewalk', 'pavement', 'footpath', '', '', '', '', '', '', '']),

    new Word(150, 'путь', '', ['way', 'path', 'road', 'pathway', 'track', '', '', '', '', '']),
    new Word(151, 'сад', '', ['garden', 'yard', 'grounds', '', '', '', '', '', '', '']),
    new Word(152, 'парк', '', ['park', 'garden', 'yard', '', '', '', '', '', '', '']),
    new Word(153, 'мост', '', ['bridge', '', '', '', '', '', '', '', '', '']),
    new Word(154, 'река', '', ['river', 'stream', 'flood', '', '', '', '', '', '', '']),
    new Word(155, 'лес', '', ['forest', 'wood', '', '', '', '', '', '', '', '']),
    new Word(156, 'поле', '', ['field', 'square', '', '', '', '', '', '', '', '']),
    new Word(157, 'гора', '', ['mountain', 'mount', '', '', '', '', '', '', '', '']),
    new Word(158, 'озеро', '', ['lake', 'loch', 'lough', '', '', '', '', '', '', '']),
    new Word(159, 'море', '', ['sea', '', '', '', '', '', '', '', '', '']),

    new Word(160, 'океан', '', ['ocean', '', '', '', '', '', '', '', '', '']),
    new Word(161, 'берег', '', ['coast', 'waterfront', 'riverside', 'waterside', '', '', '', '', '', '']),
    new Word(162, 'пляж', '', ['beach', 'plage', '', '', '', '', '', '', '', '']),
    new Word(163, 'песок', '', ['sand', 'grit', '', '', '', '', '', '', '', '']),
    new Word(164, 'остров', '', ['island', '', '', '', '', '', '', '', '', '']),
    new Word(165, 'граница', '', ['border', 'borderline', 'limit', 'bound', 'boundary', '', '', '', '', '']),
    new Word(167, 'мусор', '', ['garbage', 'rubbish', 'trash', 'litter', 'refuse', '', '', '', '', '']),
    new Word(168, 'отходы', '', ['waste', 'refuse', 'tails', '', '', '', '', '', '', '']),
    new Word(169, 'камень', '', ['stone', 'rock', '', '', '', '', '', '', '', '']),
];
